name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}
          release-type: node

  build-and-deploy:
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4

      - name: Install and Build 🔧
        run: |
          pnpm i
          pnpm run build

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./dist

  release-dist:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4

      - name: Install and Build 🔧
        run: |
          pnpm i
          pnpm run build
      - name: Zip the dist folder
        run: |
          zip -r dist.zip dist

      - name: Upload dist.zip to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist.zip
          tag_name: ${{ needs.release-please.outputs.tag_name }}

      - name: Install and Build cdn-fonts 🔧
        run: |
          pnpm i
          pnpm run build:cdn-fonts
      - name: Zip the dist-cdn-fonts folder
        run: |
          zip -r dist-cdn-fonts.zip dist

      - name: Upload dist-cdn-fonts.zip to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist-cdn-fonts.zip
          tag_name: ${{ needs.release-please.outputs.tag_name }}
